/**
 * Hardcoded stand-in for the events backend only.
 * Places always come from nikola: GET {PLACES_API_BASE_URL}/places → items[].
 */

export const events = [
  {
    id: "ev-1",
    title: "Zagreb Film Festival — opening night",
    category: "film",
    date: "2026-04-12",
    time: "19:30",
    venue: "Europa Cinema",
    area: "city center",
    blurb: "Regional premieres and Q&A.",
    latitude: 45.8107,
    longitude: 15.9752,
    address: "Varšavska 3, 10000 Zagreb",
  },
  {
    id: "ev-2",
    title: "Indie gig: local bands at Močvara",
    category: "music",
    date: "2026-04-05",
    time: "21:00",
    venue: "Močvara",
    area: "Trnje",
    blurb: "Alternative club; standing room, loud.",
    latitude: 45.7967,
    longitude: 15.9855,
    address: "Trnjanski nasip bb, 10000 Zagreb",
  },
  {
    id: "ev-3",
    title: "Contemporary art opening — group show",
    category: "art",
    date: "2026-04-08",
    time: "18:00",
    venue: "Museum of Contemporary Art",
    area: "Novi Zagreb",
    blurb: "Free entry evening; expect crowds early.",
    latitude: 45.7756,
    longitude: 15.9656,
    address: "Avenija Dubrovnik 17, 10000 Zagreb",
  },
  {
    id: "ev-4",
    title: "Food truck round-up at Britanac",
    category: "food",
    date: "2026-04-19",
    time: "12:00–20:00",
    venue: "Britanac open market",
    area: "Britanac",
    blurb: "Street food and local drinks; family friendly.",
    latitude: 45.8119,
    longitude: 15.9781,
    address: "Britanski trg, 10000 Zagreb",
  },
  {
    id: "ev-5",
    title: "Guided Upper Town walk (English)",
    category: "tour",
    date: "2026-04-06",
    time: "10:00",
    venue: "Ban Jelačić Square meeting point",
    area: "Upper Town",
    blurb: "~2h; cobblestones; small group.",
    latitude: 45.8131,
    longitude: 15.9775,
    address: "Trg bana Josipa Jelačića, 10000 Zagreb",
  },
];
