/**
 * Hardcoded stand-ins for the separate "places" and "events" backends.
 * The real apps will expose these over HTTP; the agent only sees tool results.
 * Coordinates are approximate WGS84 for map pins.
 */

export const places = [
  {
    id: "pl-1",
    name: "Museum of Broken Relationships",
    type: "museum",
    area: "Upper Town",
    vibe: "quirky, emotional, indoor",
    hoursHint: "daily ~9–22",
    note: "Small museum, unique concept; good for a rainy afternoon.",
    latitude: 45.8156,
    longitude: 15.9736,
    address: "Ćirilometodska 2, 10000 Zagreb",
  },
  {
    id: "pl-2",
    name: "Maksimir Park",
    type: "park",
    area: "Maksimir",
    vibe: "nature, walking, zoo nearby",
    hoursHint: "outdoor, daylight",
    note: "Zoo at the edge; lots of paths and lakes.",
    latitude: 45.8221,
    longitude: 16.0174,
    address: "Maksimirski perivoj, Zagreb",
  },
  {
    id: "pl-3",
    name: "Tkalciceva Street",
    type: "street_cafes",
    area: "Upper Town",
    vibe: "cafes, people-watching, evening drinks",
    hoursHint: "cafes from morning; bars late",
    note: "Classic strip for coffee or aperitivo.",
    latitude: 45.8155,
    longitude: 15.9775,
    address: "Tkalčićeva ulica, 10000 Zagreb",
  },
  {
    id: "pl-4",
    name: "Zagreb Cathedral",
    type: "landmark",
    area: "Kaptol",
    vibe: "historic, photo spot",
    hoursHint: "exterior anytime; interior check mass times",
    note: "Gothic twin spires; anchors the old town skyline.",
    latitude: 45.8149,
    longitude: 15.9789,
    address: "Kaptol, 10000 Zagreb",
  },
  {
    id: "pl-5",
    name: "Dolac Market",
    type: "market",
    area: "Upper Town",
    vibe: "local food, morning energy",
    hoursHint: "best mornings Mon–Sat",
    note: "Open-air stalls above the arcade; try strukli nearby.",
    latitude: 45.8158,
    longitude: 15.9783,
    address: "Dolac 9, 10000 Zagreb",
  },
  {
    id: "pl-6",
    name: "Technical Museum Nikola Tesla",
    type: "museum",
    area: "Savska",
    vibe: "families, science, indoor",
    hoursHint: "typical museum hours",
    note: "Mine exhibit and old vehicles; good with kids.",
    latitude: 45.8013,
    longitude: 15.8947,
    address: "Savska cesta 18, 10000 Zagreb",
  },
];

export const events = [
  {
    id: "ev-1",
    title: "Zagreb Film Festival — opening night",
    category: "film",
    date: "2026-04-12",
    time: "19:30",
    venue: "Europa Cinema",
    area: "city center",
    blurb: "Regional premieres and Q&A.",
    latitude: 45.8107,
    longitude: 15.9752,
    address: "Varšavska 3, 10000 Zagreb",
  },
  {
    id: "ev-2",
    title: "Indie gig: local bands at Močvara",
    category: "music",
    date: "2026-04-05",
    time: "21:00",
    venue: "Močvara",
    area: "Trnje",
    blurb: "Alternative club; standing room, loud.",
    latitude: 45.7967,
    longitude: 15.9855,
    address: "Trnjanski nasip bb, 10000 Zagreb",
  },
  {
    id: "ev-3",
    title: "Contemporary art opening — group show",
    category: "art",
    date: "2026-04-08",
    time: "18:00",
    venue: "Museum of Contemporary Art",
    area: "Novi Zagreb",
    blurb: "Free entry evening; expect crowds early.",
    latitude: 45.7756,
    longitude: 15.9656,
    address: "Avenija Dubrovnik 17, 10000 Zagreb",
  },
  {
    id: "ev-4",
    title: "Food truck round-up at Britanac",
    category: "food",
    date: "2026-04-19",
    time: "12:00–20:00",
    venue: "Britanac open market",
    area: "Britanac",
    blurb: "Street food and local drinks; family friendly.",
    latitude: 45.8119,
    longitude: 15.9781,
    address: "Britanski trg, 10000 Zagreb",
  },
  {
    id: "ev-5",
    title: "Guided Upper Town walk (English)",
    category: "tour",
    date: "2026-04-06",
    time: "10:00",
    venue: "Ban Jelačić Square meeting point",
    area: "Upper Town",
    blurb: "~2h; cobblestones; small group.",
    latitude: 45.8131,
    longitude: 15.9775,
    address: "Trg bana Josipa Jelačića, 10000 Zagreb",
  },
];
